title: Morgan Jones - Academic Website
description: Lecturer in Machine Learning and Control Theory at the University of Sheffield
url: "http://yourwebsite.com"  # Replace with your actual URL
baseurl: ""
theme: minima
