title: Morgan Jones - Academic Website
description: Lecturer in Machine Learning and Control Theory at the University of Sheffield
url: "https://drmorganjones.github.io/lab"  # Replace with your actual URL
baseurl: "https://drmorganjones.github.io/lab"
theme: minima
