title: Morgan Jones - Academic Website
description: Lecturer in Machine Learning and Control Theory at the University of Sheffield
url: "https://drmorganjones.github.io"  # Root URL of your GitHub Pages site
baseurl: "/lab"  # The subdirectory where your site is located
theme: minima
